esphome:
  name: zeroconf-example
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source: components
#  - source:  github://thegroove/esphome-serial-server@main

logger:
  baud_rate: 0  # disable serial logging if you're using the standard TX/RX pins for your serial peripheral

# requires uart to be set up:
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 115200

serial_server:
  port: 8888  # optional, default is 8888
  multi_client: false  # optional, default is false. Set to true to allow multiple simultaneous connections

# optional binary sensor to monitor serial connection:
binary_sensor:
  - platform: serial_server
    name: My serial server
